title: Teaching & Learning with NWB Datasets
logo: _images/nwb_learning.png
only_build_toc_files: true
repository:
  url: https://github.com/nwb4edu/nwb4edu.github.io
  branch: master
launch_buttons:
  colab_url: "https://colab.research.google.com"
  thebe                  : true
  jupyterhub_url: "https://hub.dandiarchive.org/"

execute:
  execute_notebooks: cache
  allow_errors: true
  timeout: 180
  exclude_patterns:
    - 'Lesson_3/01-Obtaining_Data_For_Single_Cells.ipynb'
    - 'Lesson_3/02-Analyzing_Computed_Features.ipynb'
    - 'Lesson_4/01-Retrieving_Brain_Observatory_Data.ipynb'
    - 'Lesson_4/02-Analyzing_Two_Photon_Data.ipynb'
    - 'Lesson_4/03-Correlations_in_Two_Photon_Data.ipynb'
    - 'Lesson_5/01-PlaceFields.ipynb'
