title: Teaching & Learning with NWB Datasets
logo: /Users/ashley/Documents/nwb4edu.github.io/nwb_learning.png
author:  
only_build_toc_files: true
repository:
  url: https://github.com/nwb4edu/nwb4edu.github.io
  branch: master
launch_buttons: 
  colab_url: "https://colab.research.google.com"
  thebe                  : true
